// const affirmations = [
//     "You got this!",
//     "You're a smart cookie!",
//     "I believe in you!",
//     "Everything has cracks - that's how the light gets in.",
//     "You are more capable than you think!",
//     "If everything was easy you'd be bored!",
//     "I admire you for taking this on!",
//     "You're doing a great job!",
//     "It'll feel magical when it's done!",
//     "I'm rooting for you!",
//     "Your mind is full of brilliant ideas and your life full of brilliant actions!",
//     "You make a difference in the world by simply existing in it!",
//     "You are worthy and deserving of respect!",
//     "You know more than you knew yesterday!",
//     "Your life is already a miracle of chance waiting for you to shape its destiny!",
//     "Nothing is impossible. The word itself says 'I’m possible!'",
//     "You can do it!",
//     "It is not a sprint, it is a marathon. One step at a time!",
//     "Success is the progressive realization of a worthy goal!",
//     "People with goals succeed because they know where they’re going!",
//     "All you need is the plan, the roadmap, and the courage to press on to your destination.",
//     "The opposite of courage in our society is not cowardice... it is conformity.",
//     "The path to success is to take massive, determined action.",
//     "It’s what you practice in private that you will be rewarded for in public.",
//     "Small progress is still progress!.",
//     "Starting is the most difficult step - but you can do it!",
//     "Don't forget to enjoy the journey.",
//     "Dreams don't work unless you take action. The surest way to make your dreams come true is to live them.",
//     "When you do the things in the present that you can see, you are shaping the future that you are yet to see.",
//     "The real measure of intelligence is action!",
//     "Your actions speaks so loudly that you need not say anything else",
//     "Your thought is illusion, your action is the truth.",
//     "When you take action on your goals, gorgeous avenues gets lined up for you.",
//     "Your persistent actions are the bridge between mind and matter, between the inner and the outer.",
//     "Change brings faster results than chance.",
//     "You can't have a detailed plan ahead of everything in life; just go do it!",
//     "Let’s keep handing out love and compassion and kindness, and let’s do this with more than just our words: Let’s do it with our actions.",
//     "Information and action combined are indestructible.",
//     "Be bold and daring. Go after what you want and create massive joy in your life.",
//     "An action taken with positive thoughts will never produce negative results.",
//     "We cannot change the past. We can only take action in the present and, therefore, change the future.",
//     "It is where you want to be in the next five years, not where you are now.",
//     "A definite recipe for success is when you take persistent action on a strong definite goal.",
//     "Courage is the ability to take bold action in spite of fear.",
//     "Have high hopes for the future; take action and it will be a reality.",
//     "This world is not here for you; you are here for it.",
//     "The secret of your future is hidden in your daily routines.",
//     "To change one's life: Begin now. Be bold. No exceptions.",
//     "The best way to create a future is to set a goal and take action",
//     "Have an intention, take action, and then learn on the way to success.",
//     "In order to get positive results, fill your mind with positive thoughts and take action.",
//     "If it must be enjoyed, then it must be done. And if it must be done, then it must be done well. If it is done well, it is enjoyed well.",
//     "The only impossible journey is the one you never begin!",
//     "Do you want to know who you are? Don’t ask. Act! Action will delineate and define you.",
//     "You don’t have to be great to start, but you do have to start to be great.",
//     "Dream big, start small, but most of all, start.",
//     "Small deeds done are better than great deeds planned.",
//     "Take the first step in faith. You don’t have to see the whole staircase, just take the first step.",
//     "Success seems to be connected with action. Successful people keep moving. They make mistakes but don’t quit.",
//     "You are what you do, not what you say you do.",
//     "Take action! An inch of movement will bring you closer to your goals than a mile of action.",
//     "Inaction breeds doubt and fear. Action breeds confidence and courage. If you want to conquer fear, do not sit home and think about it. Go out and get busy.",
//     "Act as if what you do makes a difference. It does.",
//     "The superior person is modest in their speech, but exceeds in their actions",
//     "There is nothing impossible to the person who will try",
//     "Do not be too timid and squeamish about your actions. All life is an experiment. The more experiments you make, the better.",
//     "Begin to be now what you will be hereafter.",
//     "Happiness lies not in the possession of things. It lies in the joy of achievement, in the thrill of creative effort.",
//     "Look within. Within is the fountain of good, and it will ever bubble up if thou will dig.",
//     "Action may not always bring happiness, but there is no happiness without action.",
//     "There are risks and costs to a program of action. But they are far less than the long-term risks and costs of comfortable inaction",
//     "To know oneself, one should assert oneself.",
//     "All our dreams can come true, if we have the courage to pursue them",
//     "I never worry about action. I only worry about inaction.",
//     "Things do not happen. Things are made to happen.",
//     "Knowing is not enough, we must apply. Willing is not enough, we must do.",
//     "Well done is better than well said.",
//     "First say to yourself what you would be, then do what you have to do.",
//     "Joy lies in the fight, in the attempt, in the suffering involved, not in the victory itself",
//     "Make at least one definite move towards your goal daily.",
//     "Happiness is not something ready-made, it comes from your actions.",
//     "A really great talent finds its happiness in execution",
//     "We are what we repeatedly do. Excellence, then, is not an act, but a habit",
//     "The more action you take, the more progress you take.",
//     "Action is the foundational key to all success",
//     "I've learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel",
//     "Words sound good, but actions speak.",
//     "If you want to master a habit, the key is repetition, not perfection",
//     "Thinking will not overcome fear, but action will.",
//     "The journey of a thousand miles begins with a single step.",
//     "The most realiable way to predict the future is to create it.",
//     "You only have control over three things in life: the thoughts you think, the images you visualize, and the actions you take.",
//     "Start where you are. Use what you have. Do what you can.",
//     "Intention + Action = Magic",
//     "The space in which we should live should be the person we are becoming now, not the person we were in the past.",
//     "Intent reveals desire. Action reveals commitment.",
//     "Sometimes you face difficulty not because you are doing something wrong, but because you are doing something right.",
//     "You didn't come this far to only come this far.",
//     "Ambition is the first step to success. The second step is action.",
// ];

// module.exports = affirmations